version: "3.8"
services:
  influxdb:
    image: influxdb:latest
    env_file:
      - .env-influxdb
    ports:
      - "8086:8086"
    volumes:
      - ./volumes/influxdb/data:/var/lib/influxdb
  grafana:
    image: grafana/grafana:latest
    env_file:
      - .env-grafana
    ports:
      - "3000:3000"
    volumes:
      - ./volumes/grafana/data:/var/lib/grafana
      - ./grafana-provisioning/:/etc/grafana/provisioning
    depends_on:
      - influxdb
