name: Build and publish

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform:
          - linux/amd64
          - linux/arm64
    steps:
    - name: Checkout Project
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/repeater-monitor:1.0.0 .
        docker push ${{ secrets.DOCKER_USERNAME }}/repeater-monitor:1.0.0
