name: Test

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: self-hosted
    steps:
    - name: Checkout Project
      uses: actions/checkout@v3
    - name: Setup Scala
      uses: olafurpg/setup-scala@v13
    - name: Run tests
      run: sbt test
